docs/extension/identity-proofs.md

Also updated the Ethereum test net example to match the DNS record.

Fixed formatting in Identity Proofs

---

website/docs/advanced/identity-proofs.md
website/docs/verifiable-document/did/raw-document.md
website/docs/verifiable-document/did/signing-document.md
website/docs/verifiable-document/issuing-document.md
website/docs/verifiable-document/raw-document.md
website/docs/verifiable-document/revoking-document.md

- change text `certificate` to `document`

chore: text updates

---

website/docs/advanced/v3/different-files.md
website/docs/advanced/v3/major-changes.md
website/docs/advanced/v3/overview.md
website/docs/advanced/v3/quick-start.md
website/sidebars.json

Start here: https://deploy-preview-63--laughing-cori-52b566.netlify.app/docs/advanced/v3/overview

feat: v3 beta program

---

website/docs/advanced/identity-proofs.md
website/docs/how-does-it-work/issuance-status.md
website/docs/verifiable-document/did/revoking-document.md

this pr:
- makes some edits to requested changes
- makes some wordings more precise.
here: https://deploy-preview-66--laughing-cori-52b566.netlify.app/

docs: make requested edits for revocation

---

website/docs/faq.md

- adds the faq for smart contract theoretical limit.

feat: add theoretical storage limit faq

---

website/docs/how-does-it-work/issuance-status.md
website/docs/verifiable-document/comparison.md
website/docs/verifiable-document/did/revoking-document-document-store.md
website/docs/verifiable-document/did/revoking-document-ocsp.md
website/sidebars.json

Added instructions for how to revoke using an OCSP responder

docs: added revoking through ocsp

---

website/docs/appendix/gas-costs.mdx
website/docs/faq.md
website/sidebars.json

Add a page on the estimation of the gas costs involved for verifiable and transferable documents.
* Add a new page called Gas Cost Estimation
* Add dynamic calculation of costs in fiat on page
* Remove gas costs in FAQ
* Add link in FAQ to the new Gas Cost Estimation page
https://www.pivotaltracker.com/story/show/178375347

docs: gas cost estimation

---

website/src/css/custom.css

fix: blockquote background color for dark scheme

---

website/docs/integrator-section/verifiable-document/did/dns.md

fixes the broken link for configuring DNS within the DID section.

fix: broken link on did section

---

website/docs/docs-section/appendix/contract-costs.mdx

"Live" gas prices and costs on the Contract Costs page.
* https://www.pivotaltracker.com/story/show/181736262

feat: live gas costs

---

website/docs/docs-section/appendix/contract-costs.mdx
website/src/components/BoxTag/index.jsx
website/src/components/FiatLabel/index.jsx
website/src/hooks/index.js
website/src/hooks/useFetchGasCost.js
website/src/hooks/useRefresh.js

Refactor the components on the current Contract Costs page so as to pave way for reusing them in an upcoming costs comparisons.
* https://www.pivotaltracker.com/story/show/181740061

refactor: components in contract costs page

---

website/docs/docs-section/appendix/savings-comparisons.mdx
website/src/components/Icon/index.jsx

- https://deploy-preview-132--laughing-cori-52b566.netlify.app/docs/docs-section/appendix/savings-comparisons#estimated-fees-on-ethereum

fix: costs arrow ui

---

website/docs/docs-section/appendix/contract-costs.mdx
website/src/components/DeploymentTypeLabel/index.jsx
website/src/css/custom.css

- Update contract cost table to the latest UI in figma https://www.figma.com/file/0emlKir1Mr245d1aJYJBDi/TradeTrust---documentation?node-id=0%3A1

feat: update ui contract cost table element

---

README.md
website/.env.example
website/.gitignore
website/docusaurus.config.js
website/package-lock.json
website/package.json

- Updated algolia credentails
- Put the api key as secret

fix: update algolia credentials

---

website/blog/penpal-v5-decentralized-renderer-react-components.md
website/blog/revocation-ocsp-responder.md

- wrong dates, fix them to their merged dates

fix: blog dates

---

website/docs/integrator-section/verifiable-document/did/signing-document.md

drag and drop a signed document rather than a wrapped document to verify

docs: update signing-document.md

---

website/docs/docs-section/appendix/savings-comparisons.mdx

https://www.pivotaltracker.com/story/show/183009422

docs: typo

---

website/docs/docs-section/appendix/savings-comparisons.mdx

- edited price unit
- this [one](https://github.com/Open-Attestation/documentation-website/pull/145) was wrong

docs: price unit

---

website/docs/developer-section/libraries/remote-files/decentralized-renderer/decentralized-renderer-react-template.md
website/docs/developer-section/libraries/remote-files/document-store.md
website/docs/developer-section/libraries/remote-files/open-attestation-cli.md
website/docs/developer-section/libraries/remote-files/open-attestation-encryption.md
website/docs/developer-section/libraries/remote-files/open-attestation-verify.md
website/docs/developer-section/libraries/remote-files/open-attestation.md
website/docs/developer-section/libraries/remote-files/token-registry.md

fix: update remote docs

---

website/docs/developer-section/libraries/remote-files/open-attestation-cli.md
website/docs/developer-section/libraries/remote-files/token-registry.md
website/docs/docs-section/appendix/contract-costs.mdx
website/docs/docs-section/appendix/savings-comparisons.mdx
website/package-lock.json
website/package.json

Update Contract cost page with Polygon cost estimates.
Removed 'Beta' from Token Registry V4 page.
Update docusaurus
Update remote documentation from token registry repo and OA-cli repo

feat: update contract cost with polygon

---

website/docs/developer-section/libraries/remote-files/open-attestation-cli.md
website/docs/developer-section/libraries/remote-files/token-registry.md
website/docs/developer-section/quickstart/create-verifiable-document-issuer.md

- update and fix docs
- build upon wayne's good work with updated demo
- remove code walkthrough as much as possible, text explain instead

fix: demo verifable document issuer

---

website/docs/developer-section/quickstart/create-verifiable-document-issuer.md

docs: text updates

---

website/docs/docs-section/faq.md

Added Section in FAQ for current OA distribution methods

feat: faq for distribution of oa documents

---

docs/lib-section/remote-files/decentralized-renderer-react-components.md
docs/lib-section/remote-files/document-store.md
docs/lib-section/remote-files/open-attestation-cli.md
src/reusables/_supported-networks.mdx

- fetch all latest readmes using `npm run build` to update documentation
- removed `mumbai` from supported networks
- added `amoy` in supported networks

chore: fetch latest readmes

---

docusaurus.config.js

- Add Google Analytics tag via [Docusaurus preset options](https://docusaurus.io/docs/3.1.1/api/plugins/@docusaurus/plugin-google-gtag#ex-config)

feat: google analytics

---

docusaurus.config.js
src/components/ContractCostTable/index.jsx
src/components/DeploymentTypeLabel/index.jsx
src/components/SavingsComparisonsTable/index.jsx
src/components/hooks/useFetchGasPrice.js

- Increase price refresh intervals to 1 minute
- Use API key for gas prices API
- Fix the `DeploymentTypeLabel` component key

fix: price issues
